config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" } # devise/omniauth_callbacksの代わりに、users/omniauth_callbacksを使用する
  resources :repositories do
    resources :file_items, only: [:show]
  end
  root to: "repositories#index"

  # deviseのログアウト
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/file_item.rb
# frozen_string_literal: true

class FileItem < ApplicationRecord
  self.inheritance_column = nil # typeカラムを使うために単一テーブル継承を無効にする

  has_closure_tree

  belongs_to :repository

  enum type: { dir: 0, file: 1 }
end

app/models/repository.rb
# frozen_string_literal: true

require 'base64'

class Repository < ApplicationRecord
  belongs_to :user
  has_many :file_items, dependent: :destroy

  def save_with_file_items(client)
    transaction do
      save && save_file_items(client)
    end
  end

  private

  def save_file_items(client, parent_file_item = nil, file_path = '')
    files = client.contents(path, path: file_path)
    files.each do |file|
      file_item_scope = parent_file_item ? parent_file_item.children : FileItem
      file_name = file[:name]
      file_type = file[:type]
      Rails.logger.debug file_type
      if file_type == 'dir'
        file_item = file_item_scope.create!(repository: self, name: file_name, type: file_type, content: nil)
        save_file_items(client, file_item, file[:path])
      else
        file_content = client.contents(path, path: file[:path])[:content]
        decoded_file_content = Base64.decode64(file_content).force_encoding('UTF-8')
        file_item_scope.create!(repository: self, name: file_name, type: file_type, content: decoded_file_content)
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[github]

  validates :uid, presence: true, uniqueness: { scope: :provider }

  has_many :repositories, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.access_token = auth.credentials.token
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/file_items_controller.rb
# frozen_string_literal: true

class FileItemsController < ApplicationController
  def show
    @file_item = FileItem.find(params[:id])
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[show edit update destroy]

  def index
    @repositories = Repository.all
  end

  def show; end

  def new
    @repository = Repository.new
  end

  def edit; end

  def create
    client = Octokit::Client.new(access_token: current_user.access_token)
    url = repository_params[:url] # 正規表現とかでチェックする必要はありそう
    repository_path = URI(url).path[1..] # /user/repository
    repository_info = client.repository(repository_path)
    repository_name = repository_info.name

    @repository = Repository.new(user: current_user, name: repository_name, path: repository_path)

    respond_to do |format|
      if @repository.save_with_file_items(client)
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @repository.destroy!

    respond_to do |format|
      format.html { redirect_to repositories_path, status: :see_other, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def repository_params
    params.require(:repository).permit(:url)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github

  # 認証した後のコールバック処理
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/file_items_helper.rb
# frozen_string_literal: true

module FileItemsHelper
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
  def root_file_items(repository)
    repository.file_items.where(parent_id: nil)
  end
end

app/views/file_items/show.html.erb
<h1>File Item Details</h1>

<p>
  <strong>Name:</strong>
  <%= @file_item.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @file_item.type %>
</p>

<p>
  <strong>Content:</strong>
  <pre><%= @file_item.content %></pre>
</p>

<%= link_to 'Back to Repository', repository_path(@file_item.repository) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Github Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.name %></strong>.
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
      <% else %>
        <%= button_to "Sign in with GitHub", user_github_omniauth_authorize_path, data: { turbo: false } %>
      <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/repositories/_file_items.html.erb
<ul>
  <% file_items.each do |file_item| %>
    <li>
      <%= link_to file_item.name, repository_file_item_path(file_item.repository, file_item) %>
      <%= render 'file_items', file_items: file_item.children %>
    </li>
  <% end %>
</ul>

app/views/repositories/_form.html.erb
<%= form_with(model: repository) do |form| %>
  <% if repository.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/_repository.html.erb
<div id="<%= dom_id repository %>">
  <p>
    <strong>User:</strong>
    <%= repository.user.name %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= repository.name %>
  </p>

  <strong>File Items:</strong>
  <%= render 'file_items', file_items: root_file_items(repository) %>
</div>

app/views/repositories/edit.html.erb
<% content_for :title, "Editing repository" %>

<h1>Editing repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Show this repository", @repository %> |
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Repositories" %>

<h1>Repositories</h1>

<div id="repositories">
  <% @repositories.each do |repository| %>
    <p>
      <%= link_to repository.name, repository %>
    </p>
  <% end %>
</div>

<%= link_to "New repository", new_repository_path %>

app/views/repositories/new.html.erb
<% content_for :title, "New repository" %>

<h1>New repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @repository %>

<div>
  <%= link_to "Edit this repository", edit_repository_path(@repository) %> |
  <%= link_to "Back to repositories", repositories_path %>

  <%= button_to "Destroy this repository", @repository, method: :delete %>
</div>